name: Update Profile README

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  update-readme:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Update README repositories section
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          python scripts/update_readme.py

      - name: Generate stats assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME_GH: ${{ github.repository_owner }}
          OUTPUT_DIR: assets
        run: |
          python scripts/generate_stats.py

      - name: Commit changes
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md assets

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "chore: update profile stats"

          git push